Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: /home/lgh/k8s_test/logs
  LogFileName: app
  LogFileExt: .log
  LogTraceEnable: false

Kubernete:
  KubeConfig: /root/.kube/config